---
# Tasks to install Zend Server
  - name: Ensure apt-get dependencies are installed
    apt: pkg={{ item }}
    with_items:
     - python-apt
     - python-pycurl
    become: true

  - name: Download Zend repository PGP key
    apt_key: id=F7D2C623 url=http://repos.zend.com/zend.key state=present
    become: true

  - include: install-zs5.yml
    when: zendserver_version|version_compare('6.0', '<')

  - include: install-zs6.yml
    when: zendserver_version|version_compare('6.0', '>=')

  - name: Create entry in bash_profile
    template: dest=/etc/profile.d/zend-server.sh src=zend-server.sh
    become: true
    when: php_cli_in_path == true

  - name: Make sure there is no entry in profile.d when selected so
    file: state=absent path=/etc/profile.d/zend-server.sh
    become: true
    when: php_cli_in_path == false

  - name: "Accept Zend Server EULA"
    command: /usr/local/zend/bin/zs-setup accept-eula
    become: true
    changed_when: false

  - name: "Set Zend Server GUI password"
    command: "/usr/local/zend/bin/zs-setup set-password {{ zendserver_gui_password }}"
    become: true
    changed_when: false
    when: zendserver_gui_password != ""
    
